# Generated by Django 2.0.13 on 2020-05-13 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('release_date', 'title')},
        ),
    ]
