# Generated by Django 2.0.13 on 2020-05-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200513_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.CharField(default='a', max_length=140, unique=True),
            preserve_default=False,
        ),
    ]
