# Generated by Django 2.0.13 on 2020-05-14 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_movie_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='writers',
        ),
    ]
